# Exercise 1: Search and Extract Elements

Write a Python program using Numpy that searches for a specific value in a 2D array and extracts the corresponding row or column. Allow the user to input the number which needs to be search

In [6]:
import numpy as np

def search_value(arr, value):
    result = np.where(arr == value)
    
    if result[0].size == 0:
        return "Element not found."
    else:
        row_index = result[0][0]
        col_index = result[1][0]
        
        print(f"The row containing {value}: {arr[row_index, :]}")
        print(f"The column containing {value}: {arr[:, col_index]}")

# Taking input for the matrix dimensions
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

matrix = []

print("Enter the elements row-wise:")

for i in range(rows):
    row = []
    for j in range(cols):
        row.append(int(input(f"Enter element at position ({i+1}, {j+1}): ")))
    matrix.append(row)

arr = np.array(matrix)

# Taking input for the element to search
search_element = int(input("Enter the element to search: "))

search_value(arr, search_element)


Enter the elements row-wise:
The row containing 5: [4 5 6]
The column containing 5: [2 5 8]


# Exercise 2: Sort and Join Arrays

Create a Python program using Numpy that generates two arrays, sorts them, and then concatenates them horizontally. Allow the user to input the size of the arrays and generate random values for the array elements.

In [12]:
# inputting the size of the arrays

row_arr1 = int(input("Enter the num of rows of 1st array ::"))
col_arr1 = int(input("Enter the num of cols of 1st array ::"))

row_arr2 = int(input("Enter the num of rows of 2nd array ::"))
col_arr2 = int(input("Enter the num of cols of 2nd array ::"))

# creating the arrays

arr1 = np.random.randint(1, 1000, (row_arr1, col_arr1))
arr2 = np.random.randint(1, 1000, (row_arr2, col_arr2))
print (f"1st array :: \n {arr1}")
print (f"2nd array :: \n {arr2}")

arr3 = np.concatenate((arr1,arr2), axis=1)
print(f"Concatenated array :: \n {arr3}")


1st array :: 
 [[393 215 726]
 [780 588 562]
 [541 232 286]]
2nd array :: 
 [[450 126 662]
 [265 268 173]
 [912 193 968]]
Concatenated array :: 
 [[393 215 726 450 126 662]
 [780 588 562 265 268 173]
 [541 232 286 912 193 968]]


# Exercise 3: Element-wise Operations

Create a Python program that uses Numpy to perform element-wise operations on a given array. Take a 1D Numpy array as input and perform operations like squaring, taking the square root, and finding the exponential of each element.

In [15]:
# defining the function for the operations
def operations(arr):
    squared = np.square(arr)
    print(f"The squared of each element :: {squared}")
    
    sqr_root = np.sqrt(arr)
    print(f"The square root of each element :: {sqr_root}")
    
    expolential = np.exp(arr)
    print(f"The exponential of each element :: {expolential}")
    
    
#taking input array
n = int(input("Enter the size of the array :: "))

#creating the array
matrix = []
for i in range(n):
    matrix.append(int(input()))

arr = np.array(matrix)

#calling the function
operations(arr)

The squared of each element :: [ 1  4  9 16]
The square root of each element :: [1.         1.41421356 1.73205081 2.        ]
The exponential of each element :: [ 2.71828183  7.3890561  20.08553692 54.59815003]
